FROM debian:latest


WORKDIR /app


RUN apt-get update && apt-get install -y gcc make procps


COPY Main.c MyGcd.h MyTests.c Makefile ./


RUN make

RUN make tests

# Specify the command to run when the container starts
CMD ["./tests"]